export const PHONE_CODES = [
  { code: 'TR', flag: '🇹🇷', dialCode: '+90',  name: 'Türkiye' },
  { code: 'US', flag: '🇺🇸', dialCode: '+1',   name: 'United States' },
  { code: 'GB', flag: '🇬🇧', dialCode: '+44',  name: 'United Kingdom' },
  { code: 'DE', flag: '🇩🇪', dialCode: '+49',  name: 'Deutschland' },
  { code: 'FR', flag: '🇫🇷', dialCode: '+33',  name: 'France' },
  { code: 'RU', flag: '🇷🇺', dialCode: '+7',   name: 'Россия' },
  { code: 'JP', flag: '🇯🇵', dialCode: '+81',  name: 'Japan' },
  { code: 'CN', flag: '🇨🇳', dialCode: '+86',  name: 'China' },
  { code: 'IN', flag: '🇮🇳', dialCode: '+91',  name: 'India' },
  { code: 'BR', flag: '🇧🇷', dialCode: '+55',  name: 'Brasil' },
  { code: 'MX', flag: '🇲🇽', dialCode: '+52',  name: 'México' },
  { code: 'CA', flag: '🇨🇦', dialCode: '+1',   name: 'Canada' },
  { code: 'AU', flag: '🇦🇺', dialCode: '+61',  name: 'Australia' },
  { code: 'CH', flag: '🇨🇭', dialCode: '+41',  name: 'Switzerland' },
  { code: 'AE', flag: '🇦🇪', dialCode: '+971', name: 'UAE' },
  { code: 'SA', flag: '🇸🇦', dialCode: '+966', name: 'Saudi Arabia' },
  { code: 'NL', flag: '🇳🇱', dialCode: '+31',  name: 'Nederland' },
  { code: 'IT', flag: '🇮🇹', dialCode: '+39',  name: 'Italia' },
  { code: 'ES', flag: '🇪🇸', dialCode: '+34',  name: 'España' },
  { code: 'PT', flag: '🇵🇹', dialCode: '+351', name: 'Portugal' },
  { code: 'PL', flag: '🇵🇱', dialCode: '+48',  name: 'Polska' },
  { code: 'SE', flag: '🇸🇪', dialCode: '+46',  name: 'Sverige' },
  { code: 'NO', flag: '🇳🇴', dialCode: '+47',  name: 'Norge' },
  { code: 'DK', flag: '🇩🇰', dialCode: '+45',  name: 'Danmark' },
  { code: 'FI', flag: '🇫🇮', dialCode: '+358', name: 'Finland' },
  { code: 'BE', flag: '🇧🇪', dialCode: '+32',  name: 'Belgium' },
  { code: 'AT', flag: '🇦🇹', dialCode: '+43',  name: 'Österreich' },
  { code: 'GR', flag: '🇬🇷', dialCode: '+30',  name: 'Ελλάδα' },
  { code: 'CZ', flag: '🇨🇿', dialCode: '+420', name: 'Česko' },
  { code: 'HU', flag: '🇭🇺', dialCode: '+36',  name: 'Magyarország' },
  { code: 'RO', flag: '🇷🇴', dialCode: '+40',  name: 'România' },
  { code: 'UA', flag: '🇺🇦', dialCode: '+380', name: 'Україна' },
  { code: 'AZ', flag: '🇦🇿', dialCode: '+994', name: 'Azərbaycan' },
  { code: 'GE', flag: '🇬🇪', dialCode: '+995', name: 'საქართველო' },
  { code: 'KZ', flag: '🇰🇿', dialCode: '+7',   name: 'Қазақстан' },
  { code: 'KR', flag: '🇰🇷', dialCode: '+82',  name: 'South Korea' },
  { code: 'SG', flag: '🇸🇬', dialCode: '+65',  name: 'Singapore' },
  { code: 'HK', flag: '🇭🇰', dialCode: '+852', name: 'Hong Kong' },
  { code: 'ID', flag: '🇮🇩', dialCode: '+62',  name: 'Indonesia' },
  { code: 'MY', flag: '🇲🇾', dialCode: '+60',  name: 'Malaysia' },
  { code: 'TH', flag: '🇹🇭', dialCode: '+66',  name: 'Thailand' },
  { code: 'PK', flag: '🇵🇰', dialCode: '+92',  name: 'Pakistan' },
  { code: 'IR', flag: '🇮🇷', dialCode: '+98',  name: 'Iran' },
  { code: 'IQ', flag: '🇮🇶', dialCode: '+964', name: 'Iraq' },
  { code: 'IL', flag: '🇮🇱', dialCode: '+972', name: 'Israel' },
  { code: 'LB', flag: '🇱🇧', dialCode: '+961', name: 'Lebanon' },
  { code: 'EG', flag: '🇪🇬', dialCode: '+20',  name: 'Egypt' },
  { code: 'ZA', flag: '🇿🇦', dialCode: '+27',  name: 'South Africa' },
  { code: 'NG', flag: '🇳🇬', dialCode: '+234', name: 'Nigeria' },
  { code: 'KE', flag: '🇰🇪', dialCode: '+254', name: 'Kenya' },
  { code: 'AR', flag: '🇦🇷', dialCode: '+54',  name: 'Argentina' },
  { code: 'CO', flag: '🇨🇴', dialCode: '+57',  name: 'Colombia' },
];

export function getDefaultPhoneCode() {
  return PHONE_CODES.find(c => c.code === 'TR');
}
