import { StyleSheet, Platform } from 'react-native';
import Colors from '../../../Constants/Colors';
import { s, vs, ms } from '../../../Constants/Responsive';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7FAFC' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: s(20),
  },
  backBtn: {
    backgroundColor: '#fff',
    padding: s(8),
    borderRadius: s(12),
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
  },
  headerTitle: { fontSize: ms(20), fontWeight: '800', color: '#1A1D1E' },
  addBtn: {
    backgroundColor: Colors.primary,
    padding: s(8),
    borderRadius: s(12),
    elevation: 3,
    shadowColor: Colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: s(5),
  },
  content: { padding: s(20) },

  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: s(24),
    padding: s(24),
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: s(15),
    marginBottom: vs(30),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(10),
  },
  summaryTitle: { fontSize: ms(15), fontWeight: '600', color: '#718096' },
  summaryAmount: { fontSize: ms(36), fontWeight: '800', color: '#1A1D1E', marginBottom: vs(5) },
  cents: { fontSize: ms(24), color: '#A0A3BD' },
  summaryDesc: { fontSize: ms(14), color: '#A0A3BD', fontWeight: '500', marginBottom: vs(20) },
  progressBarBg: {
    height: vs(12),
    backgroundColor: '#F1F2F6',
    borderRadius: s(6),
    overflow: 'hidden',
    marginBottom: vs(10),
  },
  progressBarFill: { height: '100%', backgroundColor: Colors.primary, borderRadius: s(6) },
  progressText: { fontSize: ms(13), fontWeight: '600', color: '#718096', textAlign: 'right' },

  sectionTitle: { fontSize: ms(18), fontWeight: '800', color: '#1A1D1E', marginBottom: vs(15) },
  emptyContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: s(30),
    borderRadius: s(20),
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginTop: vs(10),
  },
  emptyIconBox: {
    width: s(64),
    height: s(64),
    borderRadius: s(32),
    backgroundColor: Colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: vs(15),
  },
  emptyTitle: { fontSize: ms(16), fontWeight: '700', color: '#1A1D1E', marginBottom: vs(8) },
  emptyText: {
    color: '#718096',
    fontSize: ms(14),
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: ms(20),
  },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  bottomSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: s(30),
    borderTopRightRadius: s(30),
    paddingHorizontal: s(20),
    paddingTop: vs(10),
    paddingBottom: Platform.OS === 'ios' ? vs(50) : vs(30),
  },
  dragHandle: {
    width: s(40),
    height: vs(5),
    backgroundColor: '#E2E8F0',
    borderRadius: s(3),
    alignSelf: 'center',
    marginBottom: vs(15),
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(25),
  },
  sheetTitle: { fontSize: ms(18), fontWeight: '800', color: '#1A202C' },

  inputLabel: {
    fontSize: ms(13),
    fontWeight: '700',
    color: '#A0A3BD',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: vs(10),
  },

  catChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(16),
    paddingVertical: vs(10),
    borderRadius: s(20),
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F7FAFC',
  },
  catChipText: { fontSize: ms(14), fontWeight: '600', color: '#4A5568' },

  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: s(16),
    paddingHorizontal: s(20),
    marginBottom: vs(30),
  },
  currencySymbol: { fontSize: ms(24), fontWeight: '700', color: '#1A1D1E', marginRight: s(10) },
  amountInput: { flex: 1, fontSize: ms(32), fontWeight: '800', color: '#1A1D1E', paddingVertical: vs(15) },

  saveBtn: {
    backgroundColor: Colors.primary,
    paddingVertical: vs(18),
    borderRadius: s(16),
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: s(8),
    elevation: 4,
    marginBottom: vs(30),
  },
  saveBtnDisabled: { backgroundColor: '#A0A3BD', shadowOpacity: 0, elevation: 0 },
  saveBtnText: { color: '#fff', fontSize: ms(16), fontWeight: '700' },
});
