"""add created_at to receipt

Revision ID: 39e45508dcdc
Revises: h6c7d8e9f0a1
Create Date: 2026-05-08 13:37:42.627154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39e45508dcdc'
down_revision: Union[str, None] = 'h6c7d8e9f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_category_feedback_receipt_id'), table_name='category_feedback')
    op.drop_index(op.f('ix_category_feedback_upload_id'), table_name='category_feedback')
    op.drop_index(op.f('ix_category_feedback_user_id'), table_name='category_feedback')
    op.drop_table('category_feedback')
    op.drop_constraint(op.f('receipt_user_id_fkey'), 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key(op.f('receipt_user_id_fkey'), 'receipt', 'user', ['user_id'], ['id'])
    op.create_table('category_feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('receipt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('suggested_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('selected_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ocr_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], name=op.f('category_feedback_receipt_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], name=op.f('category_feedback_upload_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('category_feedback_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('category_feedback_pkey'))
    )
    op.create_index(op.f('ix_category_feedback_user_id'), 'category_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_category_feedback_upload_id'), 'category_feedback', ['upload_id'], unique=False)
    op.create_index(op.f('ix_category_feedback_receipt_id'), 'category_feedback', ['receipt_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('receipt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], name=op.f('notification_receipt_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('notification_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    # ### end Alembic commands ###
