"""restore notification table and add receipt created_at

Revision ID: 511dd71bfaba
Revises: 39e45508dcdc
Create Date: 2026-05-08 13:40:06.129209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511dd71bfaba'
down_revision: Union[str, None] = '39e45508dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('suggested_category', sa.String(length=50), nullable=True),
    sa.Column('selected_category', sa.String(length=50), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_feedback_receipt_id'), 'category_feedback', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_category_feedback_upload_id'), 'category_feedback', ['upload_id'], unique=False)
    op.create_index(op.f('ix_category_feedback_user_id'), 'category_feedback', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('receipt', sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'created_at')
    op.drop_table('notification')
    op.drop_index(op.f('ix_category_feedback_user_id'), table_name='category_feedback')
    op.drop_index(op.f('ix_category_feedback_upload_id'), table_name='category_feedback')
    op.drop_index(op.f('ix_category_feedback_receipt_id'), table_name='category_feedback')
    op.drop_table('category_feedback')
    # ### end Alembic commands ###
