"""add category to receipts

Revision ID: 83054aaa7147
Revises: 86e9bf936b20
Create Date: 2026-03-26 17:01:14.355004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83054aaa7147'
down_revision: Union[str, None] = '86e9bf936b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('category', sa.String(), server_default='other', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'category')
    # ### end Alembic commands ###
