"""add receipt_type to receipt

Revision ID: 86e9bf936b20
Revises: 5b10ec887cbf
Create Date: 2026-03-26 14:17:24.593784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e9bf936b20'
down_revision: Union[str, None] = '5b10ec887cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('receipt_type', sa.String(), server_default='expense', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'receipt_type')
    # ### end Alembic commands ###
